name: test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.0.0'
    - run: npm i -g npm@7.24.2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
